:sparkles: Skip to install when already installed

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -5,49 +5,51 @@
 #   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 #   eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
 # fi
-# 
+#
 # if [ -f "$HOME/.Brewfile" ]; then
 #   echo "Updating homebrew bundle"
 #   brew bundle --global
 # fi
 
 if ! command -v curl > /dev/null 2>&1; then
-	echo "curl is not found. Please install curl"
-	exit 1
-fi
- 
-if ! command -v git > /dev/null 2>&1; then
-	echo "git is not found. Please install git"
-	exit 1
+  echo "curl is not found. Please install curl"
+  exit 1
 fi
 
-git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
+if ! command -v git > /dev/null 2>&1; then
+  echo "git is not found. Please install git"
+  exit 1
+fi
+
+if [ ! -d "${HOME}/.asdf" ]; then
+  git clone https://github.com/asdf-vm/asdf.git ${HOME}/.asdf --branch v0.10.2
+fi
+
 . ~/.asdf/asdf.sh
 
 plugins=(
-	"ruby"
-	"nodejs"
-	"direnv"
-	"bat"
-	"ghq"
-	"tmux"
-	"neovim"
-	"golang"
-	"sops"
-	"saml2aws"
-	"shellcheck"
-	"ripgrep"
-	"fzf"
-	"exa"
-	"github-cli"
-	"jq"
-	"yq"
-	"starship"
-	)
+  "ruby"
+  "nodejs"
+  "direnv"
+  "bat"
+  "ghq"
+  "tmux"
+  "neovim"
+  "golang"
+  "sops"
+  "saml2aws"
+  "shellcheck"
+  "ripgrep"
+  "fzf"
+  "exa"
+  "jq"
+  "yq"
+  "starship"
+  )
 
 
 for plugin in "${plugins[@]}" ; do
-	asdf plugin add ${plugin}
+  asdf plugin add ${plugin}
 done
 
 asdf install
